steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --dockerfile=Dockerfile
  - --destination=gcr.io/$PROJECT_ID/tm:${COMMIT_SHA}
  - --destination=gcr.io/$PROJECT_ID/tm:${_KANIKO_IMAGE_TAG}
  - --cache-repo=gcr.io/$PROJECT_ID/tm/cache
  - --build-arg=GIT_TAG=${TAG_NAME}
  - --no-push=${_KANIKO_NO_PUSH}
  - --cache=${_KANIKO_USE_BUILD_CACHE}
  - ${_KANIKO_EXTRA_ARGS}
  waitFor: ['-']

timeout: 1800s

substitutions:
  _KANIKO_IMAGE_TAG: "latest"
  _KANIKO_NO_PUSH: "false"
  _KANIKO_USE_BUILD_CACHE: "true"
  _KANIKO_EXTRA_ARGS: ""

options:
  substitution_option: 'ALLOW_LOOSE'

tags:
  - tm
