#!/bin/bash

source "$(dirname "$BASH_SOURCE")/.validate"

IFS=$'\n'
files=( $(validate_diff --diff-filter=ACMR --name-only -- '*.go' | grep -v '^vendor/' || true) )
unset IFS

failed=0
for f in "${files[@]}"; do
	# we use "git show" here to validate that what's committed passes go vet
	if ! go vet "$f"; then
		failed=1
	fi
done

exit $failed